<?php
// Copyright 1999-2019. Plesk International GmbH. All rights reserved.
?>

<div id="dec2018"></div>

<script async type="text/javascript" src="<?=$this->baseUrl?>/js/main.js?<?=$this->version?>"></script>
<!--<script type="text/javascript">-->
<!--    window.onload = function () {-->
<!--        Elm.Main.init({-->
<!--            node: document.getElementById("dec2018")-->
<!--        });-->
<!--    }-->
<!--</script>-->
